spring.application.name=FixIt

#Verbindung zu PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fixit_app_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA Konfig
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
